name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Сборка запустится только тогда, когда вы создадите тег версии (например, v1.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
